FROM php:8.2-apache

# Install PHP extensions:
RUN apt-get update
#RUN docker-php-ext-install pdo pdo_mysql
#RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
#RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
#RUN docker-php-ext-install gd